[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.web"
watchPatterns = ["*.py", "requirements.txt"]

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build]
builder = "dockerfile"
watchPatterns = ["*.py", "requirements.txt"]
