[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.web"
watchPatterns = ["**"]

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
