[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.web"
watchPatterns = ["main.py", "railway_rag.py", "requirements.txt"]

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway optimization settings
[build.env]
DOCKER_BUILDKIT = "1"
