[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["Dockerfile", "start-ollama.sh"]

[deploy]
startCommand = "./start-ollama.sh"
# No healthcheck for Ollama service - it's not a web service
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
